# Generated by Django 3.2.4 on 2021-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nome')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('value', models.FloatField(verbose_name='value')),
            ],
        ),
    ]
